#
# The Zellij base image: a Next.js wrapper app with the engine already
# installed, and nothing else. It carries no content — a site image is built
# FROM this one by copying a content folder in.
#
# This is how Zellij is distributed. The source repository is private; this
# image is not, so anyone can build a site without access to the engine. It is
# also how the wrapper app is obtained without cloning: see `docker cp` below.

# --------------------------------------------------------------- engine build
FROM node:24-alpine AS engine

WORKDIR /src

# The whole repository, minus what .dockerignore excludes.
#
# A manifests-first copy would cache dependencies better, but the root manifest
# declares the example apps as workspaces and `npm ci` refuses to run without
# every one of their package.json files present. Listing them here would make
# the image build fail — confusingly, and in a file about the engine — the day
# somebody adds an example. This stage is discarded, and the image is built on
# release rather than on every commit, so the cache is worth less than the
# guarantee that it keeps working.
COPY . .

RUN npm ci --ignore-scripts \
 && npm run build --workspace @shebka/zellij

# Strip the package to what a consumer needs: the build output, the CLI, the
# stylesheet source the app imports, and the manifests. The engine's own
# sources, tests and tooling stay behind.
RUN mkdir -p /out \
 && cd engine/packages/zellij \
 && cp -r package.json next-config.mjs bin dist src /out/


# ------------------------------------------------------------------ base image
FROM node:24-alpine AS base

# Deliberately no NODE_ENV=production. This image is a builder, and npm reads
# that variable as "skip devDependencies" — which silently drops Tailwind's
# PostCSS plugin, the thing that resolves the engine's stylesheet.
ENV NEXT_TELEMETRY_DISABLED=1 \
    ZELLIJ_OUTPUT=standalone

# Which optional features the generated package.json asks for.
#
# Mathematics costs about fifty megabytes to install and diagrams about a
# hundred, and most documentation wants neither. They are optional dependencies
# of the engine, so leaving them out of the manifest means they are never
# fetched — and the engine degrades rather than failing, so a site that turns
# them off simply has no maths and no diagrams.
ARG ZELLIJ_FEATURES=none

# The engine lives outside /app so that copying a content folder into /app can
# never overwrite it.
COPY --from=engine /out /opt/zellij

WORKDIR /app

# The wrapper is generated by the engine's own scaffold rather than written
# here, so the image cannot drift from what `zellij init` produces locally.
#
# Nothing is installed. The image carries the engine and a manifest describing
# what a site will need; `npm install` happens when a site is built, which is
# also the moment the feature flags are known. That is the difference between
# an image people pull once at a hundred and eighty megabytes and one at a
# gigabyte — and the dependencies were being downloaded at build time either
# way, since a site build has to resolve its own lockfile regardless.
RUN node /opt/zellij/bin/zellij.mjs init /app --force --name zellij-site \
      --features "${ZELLIJ_FEATURES}"

# `node_modules` is left empty on purpose, engine included. Seeding it with a
# copy of /opt/zellij looks helpful and is not: npm finds a package already
# there, decides it must reconcile it, and goes to the public registry for a
# package that was never published — failing with a 404 for `@shebka/zellij`
# that reads like a broken image rather than a directory it should have ignored.
# The engine is at /opt/zellij, and `npm install` puts it where it belongs.

LABEL org.opencontainers.image.source="https://github.com/mylife-inc/Zellij" \
      org.opencontainers.image.description="Next.js wrapper with the Zellij engine. Copy a content folder into /app/content, npm install, and build." \
      org.opencontainers.image.licenses="UNLICENSED"

CMD ["node", "/opt/zellij/bin/zellij.mjs", "--help"]
