#!/usr/bin/env bash
# Generated by `sgit workflows`. Run your build steps here.
set -euo pipefail

# `scripts/build.sh` first: a repository with a scripts/ directory keeps its
# build beside its other scripts, and a build script at the root of a project
# that has one is the odd one out. The root form is still honoured — it is what
# `sgit init` writes into a repository that has nowhere better to put it.
for candidate in scripts/build.sh build.sh; do
  if [ -f "$candidate" ]; then
    exec bash "$candidate"
  fi
done

echo "No build script found. Create scripts/build.sh (or build.sh)." >&2
exit 1
